/**
 * Auto-generated palette data, from 16 OKLrCH primaries. Generated by tools/generate-palette.js.
 **/
export default [
  {
    name: "background",
    oklrch: [0.9, 0.02, 85],
    "display-p3": "color(display-p3 0.9079675462 0.8868655173 0.8370955902)",
    srgb: "#e9e2d4",
  },
  {
    name: "black",
    oklrch: [0, 0, 0],
    "display-p3": "color(display-p3 0 0 0)",
    srgb: "#000000",
  },
  {
    name: "white",
    oklrch: [1, 0, 0],
    "display-p3": "color(display-p3 1 1 1)",
    srgb: "#ffffff",
  },
  {
    name: "gray",
    oklrch: [0.65, 0, 0],
    "display-p3": "color(display-p3 0.6190818234 0.6190818234 0.6190818234)",
    srgb: "#9e9e9e",
  },
  {
    name: "red",
    oklrch: [0.5, 0.225, 30],
    "display-p3": "color(display-p3 0.7937392062 0.1966758334 0.1254202523)",
    srgb: "#dd1706",
  },
  {
    name: "orange",
    oklrch: [0.68, 0.225, 55],
    "display-p3": "color(display-p3 0.9465206294 0.5059409353 0.0004078754)",
    srgb: "#f88100",
  },
  {
    name: "brown",
    oklrch: [0.465, 0.225, 60],
    "display-p3": "color(display-p3 0.617486831 0.348872102 0.0001671899)",
    srgb: "#a25900",
  },
  {
    name: "yellow",
    oklrch: [0.85, 0.225, 95],
    "display-p3": "color(display-p3 0.9726144662 0.8235239991 0.0002237783)",
    srgb: "#fad200",
  },
  {
    name: "green",
    oklrch: [0.55, 0.225, 145],
    "display-p3": "color(display-p3 0.20926358 0.6295826967 0.1660243054)",
    srgb: "#00a02a",
  },
  {
    name: "teal",
    oklrch: [0.7, 0.225, 175],
    "display-p3": "color(display-p3 0.0002573694 0.8008038663 0.6528444761)",
    srgb: "#00c7a6",
  },
  {
    name: "dark blue",
    oklrch: [0.3, 0.225, 220],
    "display-p3": "color(display-p3 0.0001078292 0.3080092531 0.4000257924)",
    srgb: "#004e60",
  },
  {
    name: "light blue",
    oklrch: [0.55, 0.225, 255],
    "display-p3": "color(display-p3 0.1598833422 0.4873789758 0.9906816024)",
    srgb: "#0081f8",
  },
  {
    name: "indigo",
    oklrch: [0.4, 0.225, 270],
    "display-p3": "color(display-p3 0.2155112048 0.2655713942 0.8220531185)",
    srgb: "#3444da",
  },
  {
    name: "purple",
    oklrch: [0.4, 0.225, 310],
    "display-p3": "color(display-p3 0.4755721542 0.1435939423 0.6999397641)",
    srgb: "#841bb9",
  },
  {
    name: "light pink",
    oklrch: [0.85, 0.225, 325],
    "display-p3": "color(display-p3 0.9607849824 0.7282560314 1)",
    srgb: "#fcbaff",
  },
  {
    name: "hot pink",
    oklrch: [0.75, 0.225, 345],
    "display-p3": "color(display-p3 1 0.5097020734 0.8285408107)",
    srgb: "#ff8cd0",
  },
];
